version: '3.9'

services:

  app:
    build: .
    container_name: next_monolith
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://admin:admin123@postgres:5432/appdb
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: